spring.application.name=Shop-Sphere


## database con
spring.datasource.url=jdbc:mysql:///nexus_db
spring.datasource.username=root
spring.datasource.password=pavan3202

## JPA cfgs

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8383